name: ClubhouseResident

options:
  bundleIdPrefix: com.clubhouselinks
  deploymentTarget:
    iOS: "16.0"
  xcodeVersion: "15.0"
  createIntermediateGroups: true

settings:
  base:
    PRODUCT_BUNDLE_IDENTIFIER: com.clubhouselinks.resident
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "16"
    SWIFT_VERSION: "5.9"
    IPHONEOS_DEPLOYMENT_TARGET: "16.0"
    DEVELOPMENT_TEAM: 395Q3284J6
    CODE_SIGN_STYLE: Automatic
    TARGETED_DEVICE_FAMILY: "1"
    ENABLE_BITCODE: NO
    SWIFT_OPTIMIZATION_LEVEL: "-Onone"
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon

targets:
  ClubhouseResident:
    type: application
    platform: iOS

    sources:
      - path: ClubhouseResident
        excludes:
          - Info.plist
          - .idea

    info:
      path: ClubhouseResident/Info.plist
      properties:
        CFBundleDevelopmentRegion: en
        CFBundleDisplayName: "Clubhouse Links"
        CFBundleIconName: AppIcon
        CFBundleIdentifier: "$(PRODUCT_BUNDLE_IDENTIFIER)"
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "16"
        LSRequiresIPhoneOS: true
        UIRequiresFullScreen: true
        MinimumOSVersion: "16.0"
        UILaunchStoryboardName: LaunchScreen
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
          - UIInterfaceOrientationPortraitUpsideDown
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: false

    settings:
      base:
        INFOPLIST_FILE: ClubhouseResident/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_ENTITLEMENTS: ClubhouseResident/ClubhouseResident.entitlements